title: "RubyGeeks"
url: "http://rubygeeks.com"
author: "Senthil Nayagam"
email: "senthil@rubygeeks.com"
description: "meeting point for rubygeeks"

destination: ./Book

permalink: /:year/:month/:title

markdown: rdiscount
pygments: false

exclude:
  - README.markdown
  - _drafts
