title: "RubyGeeks"
url: "http://rubygeeks.com"
author: "Magesh"
email: "magesh@rubygeeks.com"

description: "meeting point for rubygeeks"

destination: ./Book

chapters: 10

permalink: /:year/:month/:title

markdown: rdiscount
pygments: false

exclude:
  - README.markdown
  - _drafts
